<div class="grid grid-cols-1 md:grid-cols-2 gap-4">
<div><label class="block text-sm font-semibold mb-1">Contract Name</label><input name="name" value="{{ old('name', $contract->name ?? '') }}" class="w-full rounded-xl border-slate-300" required></div>
<div><label class="block text-sm font-semibold mb-1">Contract No</label><input name="contract_no" value="{{ old('contract_no', $contract->contract_no ?? '') }}" class="w-full rounded-xl border-slate-300"></div>
<div><label class="block text-sm font-semibold mb-1">Customer</label><select name="customer_id" class="w-full rounded-xl border-slate-300" required><option value="">Select Customer</option>@foreach($customers as $customer)<option value="{{ $customer->id }}" @selected(old('customer_id', $contract->customer_id ?? '') == $customer->id)>{{ $customer->name }}</option>@endforeach</select></div>
<div><label class="block text-sm font-semibold mb-1">Service</label><select name="service_catalog_id" class="w-full rounded-xl border-slate-300"><option value="">Select Service</option>@foreach($catalogs as $catalog)<option value="{{ $catalog->id }}" @selected(old('service_catalog_id', $contract->service_catalog_id ?? '') == $catalog->id)>{{ $catalog->name }}</option>@endforeach</select></div>
<div><label class="block text-sm font-semibold mb-1">Region</label><select name="customer_region_id" class="w-full rounded-xl border-slate-300"><option value="">No Region</option>@foreach($regions as $region)<option value="{{ $region->id }}" @selected(old('customer_region_id', $contract->customer_region_id ?? '') == $region->id)>{{ $region->customer->name ?? '' }} - {{ $region->name }}</option>@endforeach</select></div>
<div><label class="block text-sm font-semibold mb-1">Branch / Site</label><select name="customer_branch_id" class="w-full rounded-xl border-slate-300"><option value="">No Branch</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected(old('customer_branch_id', $contract->customer_branch_id ?? '') == $branch->id)>{{ $branch->customer->name ?? '' }} - {{ $branch->name }}</option>@endforeach</select></div>
<div><label class="block text-sm font-semibold mb-1">Start Date</label><input type="date" name="start_date" value="{{ old('start_date', isset($contract) && $contract->start_date ? $contract->start_date->format('Y-m-d') : '') }}" class="w-full rounded-xl border-slate-300"></div>
<div><label class="block text-sm font-semibold mb-1">End Date</label><input type="date" name="end_date" value="{{ old('end_date', isset($contract) && $contract->end_date ? $contract->end_date->format('Y-m-d') : '') }}" class="w-full rounded-xl border-slate-300"></div>
<div><label class="block text-sm font-semibold mb-1">Support Hour</label><input name="support_hour" value="{{ old('support_hour', $contract->support_hour ?? '') }}" class="w-full rounded-xl border-slate-300" placeholder="8x5 / 12x6 / 24x7"></div>
<div><label class="block text-sm font-semibold mb-1">PM Frequency</label><select name="pm_frequency" class="w-full rounded-xl border-slate-300">@foreach(['daily','weekly','monthly','quarterly','semester','yearly','none'] as $f)<option value="{{ $f }}" @selected(old('pm_frequency', $contract->pm_frequency ?? 'monthly') === $f)>{{ ucfirst($f) }}</option>@endforeach</select></div>
<div><label class="block text-sm font-semibold mb-1">Response Minutes</label><input type="number" name="response_minutes" value="{{ old('response_minutes', $contract->response_minutes ?? '') }}" class="w-full rounded-xl border-slate-300"></div>
<div><label class="block text-sm font-semibold mb-1">Resolution Minutes</label><input type="number" name="resolution_minutes" value="{{ old('resolution_minutes', $contract->resolution_minutes ?? '') }}" class="w-full rounded-xl border-slate-300"></div>
<div><label class="block text-sm font-semibold mb-1">Status</label><select name="status" class="w-full rounded-xl border-slate-300">@foreach(['active','inactive','expired','draft'] as $s)<option value="{{ $s }}" @selected(old('status', $contract->status ?? 'active') === $s)>{{ ucfirst($s) }}</option>@endforeach</select></div>
<div class="md:col-span-2"><label class="block text-sm font-semibold mb-1">Scope</label><textarea name="scope" rows="3" class="w-full rounded-xl border-slate-300">{{ old('scope', $contract->scope ?? '') }}</textarea></div>
<div class="md:col-span-2"><label class="block text-sm font-semibold mb-1">Exclusion</label><textarea name="exclusion" rows="3" class="w-full rounded-xl border-slate-300">{{ old('exclusion', $contract->exclusion ?? '') }}</textarea></div>
</div>
<div class="mt-6 flex gap-3"><button class="px-5 py-2.5 bg-slate-900 text-white rounded-xl font-semibold">Save Contract</button><a href="{{ route('service-contracts.index') }}" class="px-5 py-2.5 bg-white border rounded-xl font-semibold">Cancel</a></div>
