<x-app-layout>
<div class="flex justify-between items-center mb-6"><div><h1 class="text-2xl font-black">Service Contracts</h1><p class="text-slate-500">Active managed service scope per customer and branch.</p></div><a href="{{ route('service-contracts.create') }}" class="px-4 py-2 bg-slate-900 text-white rounded-xl font-semibold">+ Add Contract</a></div>
@if(session('success'))<div class="mb-4 p-4 bg-green-50 border border-green-200 rounded-xl">{{ session('success') }}</div>@endif
<div class="bg-white rounded-2xl border overflow-hidden"><table class="w-full text-sm"><thead class="bg-slate-50"><tr><th class="text-left px-5 py-3">Contract</th><th class="text-left px-5 py-3">Customer / Branch</th><th class="text-left px-5 py-3">Service</th><th class="text-left px-5 py-3">SLA</th><th class="text-left px-5 py-3">Status</th><th class="text-right px-5 py-3">Action</th></tr></thead><tbody class="divide-y">
@forelse($contracts as $contract)
<tr><td class="px-5 py-4"><div class="font-bold">{{ $contract->name }}</div><div class="text-xs text-slate-500">{{ $contract->contract_no ?? '-' }}</div></td><td class="px-5 py-4">{{ $contract->customer->name ?? '-' }}<div class="text-xs text-slate-500">{{ $contract->branch->name ?? '-' }}</div></td><td class="px-5 py-4">{{ $contract->catalog->name ?? '-' }}</td><td class="px-5 py-4">{{ $contract->support_hour ?? '-' }} / {{ $contract->response_minutes ?? '-' }} min</td><td class="px-5 py-4 capitalize">{{ $contract->status }}</td><td class="px-5 py-4 text-right"><a href="{{ route('service-contracts.edit',$contract) }}" class="font-semibold">Edit</a></td></tr>
@empty<tr><td colspan="6" class="px-5 py-10 text-center text-slate-500">No service contracts.</td></tr>@endforelse
</tbody></table></div><div class="mt-4">{{ $contracts->links() }}</div>
</x-app-layout>
