<div class="grid grid-cols-1 md:grid-cols-2 gap-4">
<div><label class="block text-sm font-semibold mb-1">Service Name</label><input name="name" value="{{ old('name', $catalog->name ?? '') }}" class="w-full rounded-xl border-slate-300" required></div>
<div><label class="block text-sm font-semibold mb-1">Code</label><input name="code" value="{{ old('code', $catalog->code ?? '') }}" class="w-full rounded-xl border-slate-300"></div>
<div><label class="block text-sm font-semibold mb-1">Category</label><select name="service_category_id" class="w-full rounded-xl border-slate-300"><option value="">No Category</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('service_category_id', $catalog->service_category_id ?? '') == $category->id)>{{ $category->name }}</option>@endforeach</select></div>
<div><label class="block text-sm font-semibold mb-1">Support Hour</label><input name="default_support_hour" placeholder="8x5 / 12x6 / 24x7" value="{{ old('default_support_hour', $catalog->default_support_hour ?? '') }}" class="w-full rounded-xl border-slate-300"></div>
<div><label class="block text-sm font-semibold mb-1">Response Minutes</label><input type="number" name="default_response_minutes" value="{{ old('default_response_minutes', $catalog->default_response_minutes ?? '') }}" class="w-full rounded-xl border-slate-300"></div>
<div><label class="block text-sm font-semibold mb-1">Resolution Minutes</label><input type="number" name="default_resolution_minutes" value="{{ old('default_resolution_minutes', $catalog->default_resolution_minutes ?? '') }}" class="w-full rounded-xl border-slate-300"></div>
<div><label class="block text-sm font-semibold mb-1">Default PM Frequency</label><select name="default_pm_frequency" class="w-full rounded-xl border-slate-300">@foreach(['daily','weekly','monthly','quarterly','semester','yearly','none'] as $f)<option value="{{ $f }}" @selected(old('default_pm_frequency', $catalog->default_pm_frequency ?? 'monthly') === $f)>{{ ucfirst($f) }}</option>@endforeach</select></div>
<div><label class="block text-sm font-semibold mb-1">Status</label><select name="status" class="w-full rounded-xl border-slate-300"><option value="active" @selected(old('status', $catalog->status ?? 'active') === 'active')>Active</option><option value="inactive" @selected(old('status', $catalog->status ?? 'active') === 'inactive')>Inactive</option></select></div>
<div class="md:col-span-2"><label class="block text-sm font-semibold mb-1">Description</label><textarea name="description" rows="3" class="w-full rounded-xl border-slate-300">{{ old('description', $catalog->description ?? '') }}</textarea></div>
</div>
<div class="mt-6 flex gap-3"><button class="px-5 py-2.5 bg-slate-900 text-white rounded-xl font-semibold">Save</button><a href="{{ route('service-catalogs.index') }}" class="px-5 py-2.5 bg-white border rounded-xl font-semibold">Cancel</a></div>
